[
  {
    "code": "110000",
    "name": "北京",
    "value": ""
  },  {
    "code": "120000",
    "name": "天津",
    "value": ""
  },  {
    "code": "130000",
    "name": "河北",
    "value": ""
  },  {
    "code": "140000",
    "name": "山西",
    "value": ""
  },  {
    "code": "150000",
    "name": "内蒙古",
    "value": ""
  },  {
    "code": "21000000",
    "name": "辽宁",
    "value": ""
  },  {
    "code": "220000",
    "name": "吉林",
    "value": ""
  },  {
    "code": "230000",
    "name": "黑龙江",
    "value": ""
  },  {
    "code": "310000",
    "name": "上海",
    "value": ""
  },  {
    "code": "320000",
    "name": "江苏",
    "value": ""
  },  {
    "code": "330000",
    "name": "浙江",
    "value": ""
  },  {
    "code": "340000",
    "name": "安徽",
    "value": ""
  },  {
    "code": "350000",
    "name": "福建",
    "value": ""
  },  {
    "code": "360000",
    "name": "江西",
    "value": ""
  },  {
    "code": "370000",
    "name": "山东",
    "value": ""
  },  {
    "code": "410000",
    "name": "河南",
    "value": ""
  },  {
    "code": "420000",
    "name": "湖北",
    "value": ""
  },  {
    "code": "430000",
    "name": "湖南",
    "value": ""
  },  {
    "code": "440000",
    "name": "广东",
    "value": ""
  },  {
    "code": "450000",
    "name": "广西",
    "value": ""
  },  {
    "code": "460000",
    "name": "海南",
    "value": ""
  },  {
    "code": "500000",
    "name": "重庆",
    "value": ""
  },  {
    "code": "510000",
    "name": "四川省",
    "value": ""
  }, {
    "code": "520000",
    "name": "贵州",
    "value": ""
  },  {
    "code": "530000",
    "name": "云南",
    "value": ""
  },  {
    "code": "540000",
    "name": "西藏",
    "value": ""
  },  {
    "code": "610000",
    "name": "陕西",
    "value": ""
  }, {
    "code": "甘肃",
    "name": "620000",
    "value": ""
  },  {
    "code": "630000",
    "name": "青海",
    "value": ""
  },  {
    "code": "640000",
    "name": "宁夏",
    "value": ""
  },  {
    "code": "650000",
    "name": "新疆",
    "value": ""
  }, {
    "code": "710000",
    "name": "台湾",
    "value": ""
  },  {
    "code": "810000",
    "name": "香港",
    "value": ""
  },  {
    "code": "820000",
    "name": "澳门",
    "value": ""
  }
]